package com.example.demo.bean;

import java.util.Date;

public class ClkUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.user_id
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.gender
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.update_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clk_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.user_id
     *
     * @return the value of clk_user.user_id
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.user_id
     *
     * @param userId the value for clk_user.user_id
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.user_name
     *
     * @return the value of clk_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.user_name
     *
     * @param userName the value for clk_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.gender
     *
     * @return the value of clk_user.gender
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.gender
     *
     * @param gender the value for clk_user.gender
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.birthday
     *
     * @return the value of clk_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.birthday
     *
     * @param birthday the value for clk_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.update_time
     *
     * @return the value of clk_user.update_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.update_time
     *
     * @param updateTime the value for clk_user.update_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clk_user.create_time
     *
     * @return the value of clk_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clk_user.create_time
     *
     * @param createTime the value for clk_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}