package com.example.demo.mapper;

import com.example.demo.bean.ClkUser;

public interface ClkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    int insert(ClkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    int insertSelective(ClkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    ClkUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    int updateByPrimaryKeySelective(ClkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clk_user
     *
     * @mbg.generated Tue Jan 15 14:43:35 CST 2019
     */
    int updateByPrimaryKey(ClkUser record);
}